#!/usr/bin/env bash
# Summary: Bootstrapping
#
# Usage: dotfiles bootstrap

# Bomb out if we hit an error, ever
set -e
[ -n "$DOTFILES_DEBUG" ] && set -x

parse_options() {
  OPTIONS=()
  ARGUMENTS=()
  local arg option index

  for arg in "$@"; do
    if [ "${arg:0:1}" = "-" ]; then
      if [ "${arg:1:1}" = "-" ]; then
        OPTIONS[${#OPTIONS[*]}]="${arg:2}"
      else
        index=1
        while option="${arg:$index:1}"; do
          [ -n "$option" ] || break
          OPTIONS[${#OPTIONS[*]}]="$option"
          index=$(($index+1))
        done
      fi
    else
      ARGUMENTS[${#ARGUMENTS[*]}]="$arg"
    fi
  done
}

jobs_await() {
  local pid="$1"
  local spinners=('⠋' '⠙' '⠹' '⠸' '⠼' '⠴' '⠦' '⠧' '⠇' '⠏')
  while true; do
    for spinner in ${spinners[@]}; do
      printf "  $spinner  \r" > /dev/stderr
      sleep 0.05
    done
    if ! jobs -rp | grep "$pid" > /dev/null; then
      break
    fi
  done
}

{
  unset DEBUG

  parse_options "$@"
  for option in "${OPTIONS[@]}"; do
    case "$option" in
      "d" | "debug" )
        DEBUG=true
        ;;
    esac
  done

  if [ "${#ARGUMENTS[@]}" = "0" ]; then
    ARGUMENTS[0]=~/.bootstrap
  fi

  for target in "${ARGUMENTS[@]}"; do
    unset files
    if [ -f $target ]; then
      files=($target)
    elif [ -L $target ]; then
      files=($target)
    fi
    [ "$files" = "" ] && continue;

    for i in ${files[@]}; do
      name=$(basename $i)
      org=$(cd $(dirname $i);pwd)/$name
      if [ -n $DEBUG ]; then
        bash $org
      else
        bash -x $org
      fi
    done
  done
} &
pid=$!
jobs_await $pid
wait $pid

exit 0

# vim:set ts=8 sts=2 sw=2 tw=0:
# vim:set ft=sh:
