name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dotfiles
      run: ./bin/dotfiles install ./bundle
    - name: Check a file exists
      run: test -e ~/.zshenv
